# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andy/busestorage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andy/busestorage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy/busestorage/CMakeFiles /home/andy/busestorage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy/busestorage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named busestorage

# Build rule for target.
busestorage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 busestorage
.PHONY : busestorage

# fast build rule for target.
busestorage/fast:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/build
.PHONY : busestorage/fast

AzureStorageAdapter.o: AzureStorageAdapter.cpp.o

.PHONY : AzureStorageAdapter.o

# target to build an object file
AzureStorageAdapter.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageAdapter.cpp.o
.PHONY : AzureStorageAdapter.cpp.o

AzureStorageAdapter.i: AzureStorageAdapter.cpp.i

.PHONY : AzureStorageAdapter.i

# target to preprocess a source file
AzureStorageAdapter.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageAdapter.cpp.i
.PHONY : AzureStorageAdapter.cpp.i

AzureStorageAdapter.s: AzureStorageAdapter.cpp.s

.PHONY : AzureStorageAdapter.s

# target to generate assembly for a file
AzureStorageAdapter.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageAdapter.cpp.s
.PHONY : AzureStorageAdapter.cpp.s

AzureStorageFS.o: AzureStorageFS.cpp.o

.PHONY : AzureStorageFS.o

# target to build an object file
AzureStorageFS.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFS.cpp.o
.PHONY : AzureStorageFS.cpp.o

AzureStorageFS.i: AzureStorageFS.cpp.i

.PHONY : AzureStorageFS.i

# target to preprocess a source file
AzureStorageFS.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFS.cpp.i
.PHONY : AzureStorageFS.cpp.i

AzureStorageFS.s: AzureStorageFS.cpp.s

.PHONY : AzureStorageFS.s

# target to generate assembly for a file
AzureStorageFS.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFS.cpp.s
.PHONY : AzureStorageFS.cpp.s

AzureStorageFSEnv.o: AzureStorageFSEnv.cpp.o

.PHONY : AzureStorageFSEnv.o

# target to build an object file
AzureStorageFSEnv.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFSEnv.cpp.o
.PHONY : AzureStorageFSEnv.cpp.o

AzureStorageFSEnv.i: AzureStorageFSEnv.cpp.i

.PHONY : AzureStorageFSEnv.i

# target to preprocess a source file
AzureStorageFSEnv.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFSEnv.cpp.i
.PHONY : AzureStorageFSEnv.cpp.i

AzureStorageFSEnv.s: AzureStorageFSEnv.cpp.s

.PHONY : AzureStorageFSEnv.s

# target to generate assembly for a file
AzureStorageFSEnv.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/AzureStorageFSEnv.cpp.s
.PHONY : AzureStorageFSEnv.cpp.s

PathUtils.o: PathUtils.cpp.o

.PHONY : PathUtils.o

# target to build an object file
PathUtils.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/PathUtils.cpp.o
.PHONY : PathUtils.cpp.o

PathUtils.i: PathUtils.cpp.i

.PHONY : PathUtils.i

# target to preprocess a source file
PathUtils.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/PathUtils.cpp.i
.PHONY : PathUtils.cpp.i

PathUtils.s: PathUtils.cpp.s

.PHONY : PathUtils.s

# target to generate assembly for a file
PathUtils.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/PathUtils.cpp.s
.PHONY : PathUtils.cpp.s

buse.o: buse.cpp.o

.PHONY : buse.o

# target to build an object file
buse.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/buse.cpp.o
.PHONY : buse.cpp.o

buse.i: buse.cpp.i

.PHONY : buse.i

# target to preprocess a source file
buse.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/buse.cpp.i
.PHONY : buse.cpp.i

buse.s: buse.cpp.s

.PHONY : buse.s

# target to generate assembly for a file
buse.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/buse.cpp.s
.PHONY : buse.cpp.s

busestorage.o: busestorage.cpp.o

.PHONY : busestorage.o

# target to build an object file
busestorage.cpp.o:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/busestorage.cpp.o
.PHONY : busestorage.cpp.o

busestorage.i: busestorage.cpp.i

.PHONY : busestorage.i

# target to preprocess a source file
busestorage.cpp.i:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/busestorage.cpp.i
.PHONY : busestorage.cpp.i

busestorage.s: busestorage.cpp.s

.PHONY : busestorage.s

# target to generate assembly for a file
busestorage.cpp.s:
	$(MAKE) -f CMakeFiles/busestorage.dir/build.make CMakeFiles/busestorage.dir/busestorage.cpp.s
.PHONY : busestorage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... busestorage"
	@echo "... AzureStorageAdapter.o"
	@echo "... AzureStorageAdapter.i"
	@echo "... AzureStorageAdapter.s"
	@echo "... AzureStorageFS.o"
	@echo "... AzureStorageFS.i"
	@echo "... AzureStorageFS.s"
	@echo "... AzureStorageFSEnv.o"
	@echo "... AzureStorageFSEnv.i"
	@echo "... AzureStorageFSEnv.s"
	@echo "... PathUtils.o"
	@echo "... PathUtils.i"
	@echo "... PathUtils.s"
	@echo "... buse.o"
	@echo "... buse.i"
	@echo "... buse.s"
	@echo "... busestorage.o"
	@echo "... busestorage.i"
	@echo "... busestorage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

